### ISSUE TITLE
why follow function  don't push state in  deque ?

### ISSUE THREAD

**Issue by lweijin** [r-lyeh/fsm#2]
```
    void next(const fsm::state &state)
    {
        if(deque.size())
        {
            follow(deque.back(), state);
        }
        else
        {
            push(state);
        }
    }
```

**Comment by r-lyeh-archived** [comment]
- if there are no states in fsm, next(A); pushes the first A state and call begin(A);
- if there are states already in fsm, next(A); makes a smooth transition between current state and A state.
- note: follow(A,B); does a transition from A to B ensuring that end(A) and begin(B) methods gets called.

hope that helps. code is quite cryptic and needs indeed some documentation. i will do eventually : )

**Comment by lweijin** [comment]
thanks a lot :)
i found deque always has element, 
if i add a empty constration function in stack , and constrat cd_player() : has_cd(false),fsm() , when i try cd.fsm.start( opening ); then pause( deque.back() ); will be stop because deque is empty.
hope you can understand the poor english.

**Comment by lweijin** [comment]
do you kown how to print var in lambda function with gdb?
i use gcc4.9.2+gdb7.9 
Breakpoint 2, ant::ant()::{lambda(fsm::args const&)#1}::operator()(fsm::args const&) const () at scene_server.cpp:440
440                             std::cout << "pre-walk! distance:" << distance << std::endl;
(gdb) p distance
No symbol "distance" in current context.
(gdb) p this
No symbol "this" in current context.
(gdb)

**Comment by r-lyeh-archived** [comment]
you should do more like following to behave correctly:

``` c++
cd_player() : has_cd(false), fsm( opening ) {
}

// [...] then
cd.fsm( pause );
```

**Comment by r-lyeh-archived** [comment]
also, try `p *this` and `bt` in GDB to see where you at :D

**Comment by lweijin** [comment]
(gdb) p *this
No symbol "this" in current context.

**Comment by lweijin** [comment]
```
    void replace(const fsm::state &state)
    {
        if(deque.size())
        {
            end(deque.back());
            deque.pop_back();
        }
        deque.push_back(state);
        begin(deque.back());
    }
```

is that ok i add this function?

**Comment by lweijin** [comment]
_fsm.pop();
_fsm.push(new_state);
is that ok?

**Comment by r-lyeh-archived** [comment]
- `push()` allows you to pause current status, and queue/switch to a new one
- `pop()` allows you to terminate current status, and resume/return to a previous (pushed) state
- `push/pop` are intended for HFSM (hierarchical state machine) classes and are, therefore, optional.
- if you just want to switch/replace the current state to a different state, use `next()` instead.

**Comment by r-lyeh-archived** [comment]
related to that `p *this` ensure you are inside a method of a class. i guess you are either at main() or inside a C-ish function.

**Comment by lweijin** [comment]
Thank you so much. That's very helpful.
If you can provide another more complicated sample like sample1.cc that would be great :)
